### ISSUE TITLE
Login stopped working since May 2017

### ISSUE THREAD

**Issue by lparede** [gunna-php/sma#1]
I have been using this tool since the beggining of 2017 and all worked well since then.
In May 2017 is no longer possible to make login through this tool. Username and passsord are correct, because I can login directly through the sunnyportal website.

**Comment by lalo4ka** [comment]
same here! I can't login :(

**Comment by Lipegno** [comment]
Hey,
I manage do solved it, I made a standalone route for my case, the code is a huge mess, but probably you can find something useful. To be fair while I was developing SMA changed the order of some pages and  code method working, this approach will always be a bit sketchy, but there is no alternative right now

NOTE: this route is used to export the historical data, which is the most complex case, you can get simpler data by doing less requests and parsing for the data you wish

`app.get("/dataSMA/total/:day/:month/:year", function (req, resp) {
    
    var day   = parseInt(req.params.day)+1;
    var month = parseInt(req.params.month)-1;
    var year  = parseInt(req.params.year); 
    var now =  new Date().getTime();
    var start = (new Date(req.params.year,month,req.params.day,0,0,0,0).getTime()/1000);
    var end = (new Date(req.params.year,month,day,0,0,0,0).getTime()/1000);
    var name = "Balanço_energético_"+req.params.year+"_"+req.params.month+"_"+req.params.day+".csv";
    console.log(now+" --- "+start+" ---"+end+" ----- "+name);
      var path = "https://www.sunnyportal.com/Templates/Start.aspx?ReturnUrl=%2f";
      var body = "";
      var realTimeResponse;
      https.get(path, res => {
        res.setEncoding("utf8");
    
        res.on("data", data => {
          body += data;
        });
        res.on("end", () => {
            var $ = cheerio.load(body);
            var view_state = $('#__VIEWSTATE').attr('value');
            var view_state_generator = 'VIEW_STATE_GENERATOR';
            var user = "USER";
            var pass = "PASSWORD";
            var login = "Login";
            var access = "true";
    
            var form = {
              __VIEWSTATE: view_state,
              __VIEWSTATEGENERATOR: view_state_generator,
              ctl00$ContentPlaceHolder1$Logincontrol1$txtUserName:user,
              ctl00$ContentPlaceHolder1$Logincontrol1$txtPassword:pass,
              ctl00$ContentPlaceHolder1$Logincontrol1$LoginBtn:login,
              ctl00$ContentPlaceHolder1$Logincontrol1$ServiceAccess:access
            };
    
            var formData = querystring.stringify(form);
            var contentLength = formData.length;
    
              request({
                  headers: {
                    'Content-Length': contentLength
                    ,'Content-Type': 'application/x-www-form-urlencoded'
                    ,'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8'
                    ,'Accept-Encoding': 'gzip, deflate, br'
                    ,'Accept-Language': 'pt-PT,pt;q=0.9,en-GB;q=0.8,en;q=0.7,en-US;q=0.6'
                    ,'Cache-Control': 'max-age=0'
                    ,'Connection': 'keep-alive'
                    ,'Host': 'www.sunnyportal.com'
                    ,'Origin': 'https://www.sunnyportal.com'
                    ,'Referer': 'https://www.sunnyportal.com/Templates/Start.aspx?logout=true'
                    ,'Upgrade-Insecure-Requests': '1'
                    , 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36'
                  },
                  uri: 'https://www.sunnyportal.com/Templates/Start.aspx?logout=true',
                  jar: cookieJar,
                  body: formData,
                  method: 'POST'
                }, function (err, response, body) {
                    console.log(cookieJar);                      
                      var form = {
                        __EVENTTARGET:'',
                        ctl00$ContentPlaceHolder1$UserControlShowInverterSelection1$DeviceSelection$HiddenPlantOID : PLANT OID,
                        ctl00$ContentPlaceHolder1$UserControlShowInverterSelection1$SelectedIntervalID:'3',
                        ctl00$ContentPlaceHolder1$UserControlShowInverterSelection1$UseIntervalHour:'0',
                        ctl00$ContentPlaceHolder1$UserControlShowInverterSelection1$_datePicker$textBox: req.params.dia+'-'+req.params.mes+'-'+req.params.ano,
                        ctl00$HiddenPlantOID : 'PLANT OID'
                      }                        
                      request({
                        method : 'POST',
                        strictSSL : false,
                        form : form,
                        jar : cookieJar,
                        uri :'https://www.sunnyportal.com/FixedPages/InverterSelection.aspx'
                        },function (err, response, body) {
                            if(err)
                              console.log('error selecting inverter');                          
                              request({
                                method : 'GET',
                                strictSSL : false,
                                jar : cookieJar,
                                uri :'https://www.sunnyportal.com/FixedPages/HoManEnergyRedesign.aspx'  //START EDN CURRENT
                               },function (err, response, body) {
                                if(err)
                                   console.log('error balance');                               
                                   request({
                                  method : 'GET',
                                  strictSSL : false,
                                  jar : cookieJar,
                                  uri :'https://www.sunnyportal.com/PortalCharts/Core/PortalChartsAPI.aspx?id=mainChart&presetting=day&scta=true&t='+now  //START EDN CURRENT
                                 },function (err, response, body) {
                                  if(err)
                                    console.log('error day');                               
                                  request({
                                    method : 'GET',
                                    strictSSL : false,
                                    jar : cookieJar,                                                                                                   // 1524337520000 
                                    uri :'https://www.sunnyportal.com/PortalCharts/Core/PortalChartsAPI.aspx?id=mainChart&xf='+start+'&xt='+end+'&t='+now
                                  },function (err, response, body) {
                                    if(err)
                                      console.log('error chart');
                                        if(err)
                                         console.log('error legend');                
                                        
                                         request({
                                            method : 'GET',
                                            strictSSL : false,
                                            jar : cookieJar,
                                            uri :'https://www.sunnyportal.com/Templates/DownloadDiagram.aspx?down=homanEnergyRedesign&chartId=mainChart',
                                          },function (err, response, body) {
                                            if(err)
                                            console.log('error init down');   
                                            resp.end(JSON.stringify(parseDataSMA(response.body.toString(),day,month,year)));
                                                                               });    
                                    });      
                              });
                       });          
                 });
               });
            });
          });              
     });
`

**Comment by kwanchaiPKG** [comment]
hi
I can't login.
It error login.

Previous comments.
how to run it.

**Comment by No0ne** [comment]
Found out that after changing the user-agent to e.g. 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0' the login is working again.

https://github.com/gunna-php/sma/blob/7344d7700bb5cb7fe8c4120918262ae2b4ba8950/src/SunnyPortal.php#L124

**Comment by daniellienert** [comment]
Hey there, 
thanks @srmiles for the script. Got it working with the suggested change from @No0ne. Currently working on improving and stabilizing the package in #3 .
